GET http://localhost:5243/list/

###

GET http://localhost:5243/list/6744d1e9b75fd9f9876be5f6

###

POST http://localhost:5243/list/newlist

###

POST http://localhost:5243/list/fromlist
Content-Type: application/json

{
  "id": {
    "timestamp": 0,
    "creationTime": "1970-01-01T00:00:00Z"
  },
  "title": "anime list",
  "items": [
    {
      "name": "100-man no inochi no ue ni ore wa tatteiru",
      "groups": [
        "0",
        "3",
        "12",
        "20"
      ],
      "groupPositions": {
        "0": 0,
        "3": 34,
        "12": 0,
        "20": 0
      },
      "properties": [
        {
          "name": "last watched",
          "data": ""
        },
        {
          "name": "japanese title",
          "data": "100万の命の上に俺は立っている"
        },
        {
          "name": "english title",
          "data": "i'm standing on 1,000,000 lives"
        },
        {
          "name": "notes",
          "data": ""
        }
      ]
    },
    {
      "name": "5-toubun no hanayome",
      "groups": [
        "0",
        "2",
        "13",
        "15",
        "20"
      ],
      "groupPositions": {
        "0": 1,
        "2": 97,
        "13": 0,
        "15": 0,
        "20": 1
      },
      "properties": [
        {
          "name": "last watched",
          "data": "11/28/2023"
        },
        {
          "name": "japanese title",
          "data": "五等分の花嫁"
        },
        {
          "name": "english title",
          "data": "the quintessential quintuplets"
        },
        {
          "name": "notes",
          "data": ""
        }
      ]
    },
    {
      "name": "86",
      "groups": [
        "0",
        "2",
        "12",
        "16",
        "21"
      ],
      "groupPositions": {
        "0": 2,
        "2": 40,
        "12": 1,
        "16": 0,
        "21": 0
      },
      "properties": [
        {
          "name": "last watched",
          "data": "2/8/2023"
        },
        {
          "name": "japanese title",
          "data": "86―エイティシックス―"
        },
        {
          "name": "english title",
          "data": ""
        },
        {
          "name": "notes",
          "data": ""
        }
      ]
    }
  ],
  "groups": {
    "a": {
      "id": "a9e6ed0f-95ab-46ab-8a79-812b11632b8b",
      "name": "alphabetically",
      "subGroups": [],
      "size": 0,
      "parent": "",
      "position": 0,
      "settings": {
        "numbered": false,
        "autoSort": true,
        "sortByProperty": "",
        "sortAscending": true,
        "collapse": true
      }
    },
    "b": {
      "id": "a9e6ed0f-95ab-46ab-8a79-812b11632b8b",
      "name": "alphabetically2",
      "subGroups": [],
      "size": 0,
      "parent": "",
      "position": 0,
      "settings": {
        "numbered": false,
        "autoSort": true,
        "sortByProperty": "",
        "sortAscending": true,
        "collapse": true
      }
    },
    "c": {
      "id": "a9e6ed0f-95ab-46ab-8a79-812b11632b8b",
      "name": "alphabetically3",
      "subGroups": [],
      "size": 0,
      "parent": "",
      "position": 0,
      "settings": {
        "numbered": false,
        "autoSort": true,
        "sortByProperty": "",
        "sortAscending": true,
        "collapse": true
      }
    }
  },
  "properties": [
    "last watched",
    "japanese title",
    "english title",
    "notes"
  ]
}

###

POST http://localhost:5243/list/6744d1e9b75fd9f9876be5f6/item
Content-Type: application/json

{
    "name": "86",
    "groups": ["8faa02f1-eb24-48b1-809b-c9cc8704367f"],
    "groupPositions": {"8faa02f1-eb24-48b1-809b-c9cc8704367f": 0 },
    "properties": [
        { "name": "last watched", "data": "2/8/2023" },
        { "name": "japanese title", "data": "86―エイティシックス―" },
        { "name": "english title", "data": "" },
        { "name": "notes", "data": "" }
    ]
}

###

POST http://localhost:5243/list/6744d1e9b75fd9f9876be5f6/group
Content-Type: application/json

{
    "name": "alphabetically",
    "subGroups": [],
    "size": 31,
    "parent": "",
    "position": 0,
    "settings": { "numbered": false, "autoSort": true, "sortByProperty": "", "sortAscending": true, "collapse": true }
}

###

PUT http://localhost:5243/list/6744d1e9b75fd9f9876be5f6
Content-Type: application/json

{
    "title": "anime list2",
    "properties": ["last watched", "japanese title", "english title", "notes"]
}

###

PUT http://localhost:5243/list/6744d1e9b75fd9f9876be5f6/item/2
Content-Type: application/json

{
    "name": "86 b",
    "groups": [0, 2, 12, 16, 21],
    "groupPositions": { "0": 2, "2": 40, "12": 1, "16": 0, "21": 0 },
    "properties": [
        { "name": "last watched", "data": "2/8/2023" },
        { "name": "japanese title", "data": "86―エイティシックス―" },
        { "name": "english title", "data": "" },
        { "name": "notes", "data": "" }
    ]
}

###

PUT http://localhost:5243/list/6744d1e9b75fd9f9876be5f6/group/b9ec34af-ae4d-43cd-a00c-6acb16bfad29
Content-Type: application/json

{
    "name": "alphabetically2",
    "position": 0,
    "settings": { "numbered": false, "autoSort": true, "sortByProperty": "", "sortAscending": true, "collapse": true }
}

###

DELETE http://localhost:5243/list/6744d1e9b75fd9f9876be5f6/item/0

###

DELETE http://localhost:5243/list/6744d1e9b75fd9f9876be5f6/group/b9ec34af-ae4d-43cd-a00c-6acb16bfad29